#!/bin/bash

#set -x

argumentCount="$#"

if [ "$argumentCount" = "1" ] #checks if there was one argument passed.
then
	inputFile="./inputFile$$"
	cat > "$inputFile" #adds the stdin data to be stored in datafile(process ID).
elif [ "$argumentCount" = "2" ]  #checks if there were two arguments passed.
then
	if [ -s $2 ] #checks if files exists and has contents.
	then
		if [ -r $2 ] #checks if file is readable.
		then
			inputFile="./inputFile$$" #stores the input filepath argumment.
			cp $2 $inputFile
		else 
			echo "ERROR: File was not readable." 1>&2
			exit 1
		fi
	else 
		echo "ERROR: File is empty or not readable." 1>&2 # write error message to stderror and exit with value of 1.
		exit 1
	fi
else 
	echo "Usage stats \{-row\|-col\} \[file\]" 1>&2 #write error message to 
	exit 1 #standard error and return 1 for too many arguments passed.
fi

trap "rm -f \"$inputFile\" \"$tempRow\"; echo 'Trapped a signal and Exiting.'; exit 1;" INT HUP TERM #traps and terminates file storing stdin data if created and unexpectedly quits.

if [[ -s  $inputFile ]] #checks if file exists.
then
	if [[ $1 == -r* ]] #checks if user asked for row calculations.
	then
		echo -e "Average\tMedian"
		while read line #while not the end of the file, read the next row.
		do
			count=$(echo "$line" | wc -w)
			median=$(echo "$line" | tr '\t' '\n'  | sort -n | tr '\n' '\t' | cut -f $(((count/2+1))))
			sum=0 
			average=0
			for everyNumber in $line 
			do
				sum=$(($sum + $everyNumber))
			done
			
			if [ $sum -eq 0 ]
			then
				break
			fi
			
			average=$(($sum / $count))	
			if [ $(((sum%$average)*2)) -ge $count ] 
			then
				((average++))
			fi	
			echo -e "$average\t$median " #print average and median for each row
		
		done < "$inputFile"

		rm -f "$inputFile"

	elif [[ $1 == -c* ]] #checks if the users wants the data sorted by columns.
	then
		echo -e "Average\tMedian"
		columnNumber=1
		tempRow="./tempRow$$"
		while read line #while not the end of file.
		do
			for number in $line
			do
				cut -f $columnNumber $inputFile | sort -n | tr '\n' '\t' >> $tempRow
				echo ""	>> $tempRow
				((columnNumber++))
			done
			break
		done <"$inputFile"
		
		while read line 
		do 
			average=0
			sum=0
			count=$(echo "$line" | wc -w)
			if [ $count -eq 0 ]
			then
				break
			fi
			
			median=$(echo "$line" | cut -f $(((count/2+1))))
			
			for number in $line
			do
				sum=$(($sum+$number))
			done
			
			average=$(($sum/$count))

			if [ $((($sum%$average)*2)) -ge $count ]
			then
				((average++))
			fi
			
			echo -e "$average\t$median"

		done < $tempRow
		
		rm -f "$tempRow"	
		rm -f "$inputFile"
	else
		rm -f "$inputFile"
		echo "Usage: stats \{-rows\|-cols\} \[file\]" 1>&2
		exit 1
	fi
else
	echo "ERROR: File does not exist." 1>&2
	exit 1
fi
